name: example
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  freezed: ^2.2.1
  freezed_annotation: ^2.0.3
  fp_state_generator:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.3.3

dependency_overrides:
  fp_state_generator:
    path: ../



flutter:


  uses-material-design: true
