targets:
  $default:
    builders:
      fp_state_generator:
        enabled: true
        generate_for:
          exclude:
            - test
            - example
          include:
            - lib/**/*.dart
            - test/integration/*
            - test/integration/**/*
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - "type=lint"

builders:
  fp_state_generator:
    import: "package:fp_state_generator/builder.dart"
    builder_factories: ["fpStateBuilder"]
    build_extensions: { ".dart": [".fpState.dart"] }
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen:combining_builder"]
    runs_before: ["source_gen|combining_builder"]
