name: fp_state_generator

description: "Code generation"
version: 0.0.1
homepage: https://pub.dev/packages/fp_state_generator
repository: https://github.com/jack-fan1991/flutter_fp_state_generator


environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ">=5.13.0 <7.0.0"
  build: ^2.0.0
  source_gen: ^1.2.3
  change_case: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_test: ^2.1.5
  build_runner: ^2.3.3


dependency_overrides:
  # fp_state_annotation:
  #   path: ../fp_state_annotation

flutter:
